// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd_drive.proto

/*
Package seguepb is a generated protocol buffer package.

It is generated from these files:
	cmd_drive.proto
	segue.proto
	sensor_ultrasonic.proto

It has these top-level messages:
	CmdDriveData
	Message
	MessageEnvelope
	SensorUltraSonicData
*/
package seguepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CmdDriveData struct {
	Speed uint32 `protobuf:"varint,1,opt,name=speed" json:"speed,omitempty"`
}

func (m *CmdDriveData) Reset()                    { *m = CmdDriveData{} }
func (m *CmdDriveData) String() string            { return proto.CompactTextString(m) }
func (*CmdDriveData) ProtoMessage()               {}
func (*CmdDriveData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CmdDriveData) GetSpeed() uint32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func init() {
	proto.RegisterType((*CmdDriveData)(nil), "seguepb.CmdDriveData")
}

func init() { proto.RegisterFile("cmd_drive.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 87 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xce, 0x4d, 0x89,
	0x4f, 0x29, 0xca, 0x2c, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0x4d,
	0x2f, 0x4d, 0x2d, 0x48, 0x52, 0x52, 0xe1, 0xe2, 0x71, 0xce, 0x4d, 0x71, 0x01, 0x49, 0xb9, 0x24,
	0x96, 0x24, 0x0a, 0x89, 0x70, 0xb1, 0x16, 0x17, 0xa4, 0xa6, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0xf0, 0x06, 0x41, 0x38, 0x49, 0x6c, 0x60, 0x5d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8,
	0x7d, 0x78, 0x58, 0x48, 0x00, 0x00, 0x00,
}
